default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: <%= ENV['POSTGRES_PASS'] %>
  pool: 5

development:
  <<: *default
  database: turninggreen_dev

test:
  <<: *default
  database: turninggreen_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
  database: "rootup_production"
